version: "3"

networks:
  frontend_network:
  backend_network:

services:
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    networks:
      - frontend_network
    environment: 
      - REACT_APP_API=http://localhost:5000
    depends_on:
      - server 

  server:
    build:
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment: 
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB_NAME=employeeSystem
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - mongodb 

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017" 
    volumes:
      - mongodb_data:/data/db 
    networks:
      - backend_network

volumes:
  mongodb_data: 
